language: python
python:
- '3.3'
- '3.4'
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: kirillsulim
  password:
    secure: gWPJcIz3z10xofphMyiZLNGn2BWqRU8nqKPDanYf3+JKO1RVIVP/SGDzvQhBNuPMj2U2erWRX/I4LAFk9epSzn+JAabaNO7hxFrBDfC/boiuRS1YXRr938zba3T0QIfbTlkG4j5/anuJzxPPAODD6PjjPiieIMzN75G8kiG8lI3IfQMRJtqBw02CMUlp3es3VAA9uQStEHKzvbEiM5X/p0e8bk/ZXLwHfHOtEjxfaunxMm+Amqqpjpd9eOB9p5RocKZz6IUtlNoOw5tLU3W2lcTzB0n53tP4Sf/h1v/tUNA7vza0ibL4JC1wN2zGoNoDn8In/t9uT7mpdoUGCpV4RLHyDb7+Jh7qYpw24i+Ha5e89e2MXUkj+/Ax+D0b2qTDHmgfhPn3Z6PGQwpKNVCIqWWLirThothvvEqXvK2Ax16hjzuNoS7B08mv4yxbs1Qvrcfen9Y0wKBXiok6HSqSLSHm0Tg43d13/8WYjEoIAhaYWAAZgtcEpISW32lQp8qW2QhmEn2AdN1rEOZtDS60QS+U3TqnfmYSL3NXo1YIhfiMVwYfiD6ClbEI1j4qobv0xlfTgOrn3C/lk2KksgWxG6Ixu8dpvSmIzaWgZg5lmJe5I//dhWPt8p9BJrHQ7N0qkkF13BfmIiQ6sKSzaeSD3c67KuZgzJugv3xKf/E87T4=
  on:
    tags: true
    repo: dogebuild/dogebuild-fpc
